### ISSUE TITLE
crick fails to install with numpy >= 1.26

### ISSUE THREAD

**Issue by kinow** [dask/crick#42]
**Describe the issue**:

Creating a mamba env that contains simply `numpy` , and with `crick==v0.0.4` as a dependency fails with: `No module named 'numpy.distutils'`

**Minimal Complete Verifiable Example**:

```yaml
name: my_env
channels:
  - conda-forge
dependencies:
  - python
  - numpy
  - xarray
  - dask
  - zarr
  .......
  - pip
  - pip:
    - -e .[all]
```

And in `setup.py` we have:

```py
    install_requires=[
     ...........
        "crick==0.0.4",
    ],

```

**Anything else we need to know?**:

We fixed it by pinning Numpy to <1.26. The Numpy 1.26 notes explain about the distutils replacement/drop: https://github.com/numpy/numpy/releases/tag/v1.26.0

Here's a commit where they updated example code that used the `get_info` function used in `crick`'s `setup.py`.

https://github.com/numpy/numpy/commit/8c0e2bc4746417269c9cca105c729a08a0349a7e

**Environment**:

- Dask version: 2023.12.0
- Python version: 3.11.6
- Operating System: Ubuntu LTS
- Install method (conda, pip, source): Conda + Pip
